
# ApiGateway -> graphql resource -> POST method -> Cloudformation overriding some config
ApiGatewayMethodGraphqlPost:  # <- Had to look this up "the hard way"
  Type: 'AWS::ApiGateway::Method'
  Properties:
    AuthorizationType: AWS_IAM  #sets authorization to AWS_IAM
    Integration:
      Credentials: 'arn:aws:iam::*:user/*' #sets "Invoke with caller credentials" to true

# ApiGateway -> graphql resource -> GET method -> Cloudformation overriding some config
ApiGatewayMethodGraphqlGet:  # <- Had to look this up "the hard way"
  Type: 'AWS::ApiGateway::Method'
  Properties:
    AuthorizationType: AWS_IAM  #sets authorization to AWS_IAM
    Integration:
      Credentials: 'arn:aws:iam::*:user/*' #sets "Invoke with caller credentials" to true